### ISSUE TITLE
Опечатки в переводе

### ISSUE THREAD

**Issue by P1nkL1on** [Snarls-at-Fleas/ACKSSRD-Ru#3]
- [Заклинания](https://github.com/Snarls-at-Fleas/ACKSSRD-Ru/blob/main/chapter-5.html)
  - `Плость в камень`, скорее всего "плоть в камень"

**Comment by Snarls-at-Fleas** [comment]
Да, все так, но эту версию уже не имеет смысла править. Я работаю над переводом ACKS II
Новости здесь: https://t.me/snarl5
